# Generated by Django 6.0.4 on 2026-04-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_system_backup_schedule_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetitemtype',
            options={
                'ordering': ['name'],
                'permissions': [
                    ('view_assettrackercategory', 'Can view asset tracker category'),
                ],
            },
        ),
    ]
