# Generated by Django 6.0.4 on 2026-04-28 00:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_supportticket_archived_at_supportticket_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasefile',
            name='file',
            field=models.FileField(storage=core.models.ProjectDatabaseStorage(), upload_to=core.models.database_file_upload_to),
        ),
    ]
