from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetDoneView
from django.urls import path

from .system_views import (
    system_backup_delete,
    system_backup_download,
    system_backup_open,
    system_backup_restore,
    system_backup_run_now,
    system_hub,
)
from .ticketing_views import (
    support_ticket_add_message,
    support_ticket_create,
    support_ticket_detail,
    support_ticket_update_requested_priority,
    support_ticket_update_support,
    support_tickets_bulk_archive,
    support_tickets_bulk_delete,
    support_tickets_list,
)

from .views import (
    accountability_create,
    accountability_decide,
    accountability_item_auto_fill,
    accountability_list,
    accountability_pending_bulk_decide,
    accountability_report_list,
    accountability_report_list_csv,
    accountability_report_summary,
    accountability_report_summary_csv,
    accountability_records_bulk_action,
    accountability_return,
    assets_department_create,
    assets_department_delete,
    assets_departments_bulk_delete,
    assets_company_account_reveal,
    assets_company_accounts,
    assets_company_account_submit,
    assets_departments_list,
    assets_department_update,
    assets_generate_tags,
    assets_item_create,
    assets_item_delete,
    assets_items_bulk_delete,
    assets_variants_bulk_delete,
    assets_item_type_create,
    assets_item_type_delete,
    assets_item_types_bulk_delete,
    assets_item_type_update,
    assets_item_types_list,
    assets_item_update,
    assets_item_variants_modal,
    assets_list,
    assets_tag_document,
    assets_tag_batch_delete,
    assets_tag_batches_bulk_delete,
    clients_create,
    clients_bulk_delete,
    clients_deletion_request_approve,
    clients_deletion_request_reject,
    clients_bulk_update_status,
    clients_delete,
    clients_list,
    clients_quick_view,
    clients_quotation_document,
    clients_quotations_bulk_delete,
    clients_quote,
    clients_update,
    development_feedback_add_comment,
    development_feedback_delete,
    development_feedback_update_status,
    development_hub,
    development_patch_note_comment_add,
    development_patch_note_comment_delete,
    development_patch_note_comment_edit,
    development_patch_note_delete,
    development_patch_note_toggle_like,
    development_patch_note_update,
    development_patch_notes,
    EmailVerificationSentView,
    email_verification_otp,
    OTPVerifyView,
    fund_request_document,
    fund_request_document_download,
    fund_request_bulk_download,
    fund_request_bulk_print,
    fund_request_client_side_preview,
    finance_dashboard,
    finance_reimburstment,
    finance_summary_request,
    fund_request_print,
    fund_request_review,
    fund_request_review_pdf,
    fund_request_records,
    fund_request_records_pdf,
    fund_request_records_csv,
    fund_request_template_guide,
    fund_request_template_preview,
    fund_request_template_preview_pdf,
    fund_requests_list,
    liquidation_download,
    liquidation_bulk_print,
    liquidation_bulk_download,
    liquidation_page,
    liquidation_pdf,
    SecureLoginView,
    SecureLogoutView,
    SecurePasswordChangeView,
    SecurePasswordResetConfirmView,
    SecurePasswordResetView,
    dashboard,
    profile_page,
    landing,
    lockout_notice,
    otp_setup,
    send_email_verification,
    mark_notifications_read,
    support_lockout_center,
    notifications_feed,
    notifications_list,
    update_presence_status,
    update_user_status,
    roles_create,
    roles_delete,
    roles_list,
    roles_update,
    users_create,
    users_bulk_delete,
    users_bulk_update_role,
    users_bulk_update_status,
    users_delete,
    users_list,
    users_quick_profile,
    users_update,
    verify_email,
)

urlpatterns = [
    path('', landing, name='landing'),
    path('login/', SecureLoginView.as_view(), name='login'),
    path('login/locked/', lockout_notice, name='lockout_notice'),
    path('logout/', SecureLogoutView.as_view(), name='logout'),
    path('login/verify-otp/', OTPVerifyView.as_view(), name='otp_verify'),
    path('account/setup-2fa/', otp_setup, name='otp_setup'),
    path('account/send-verification/', send_email_verification, name='send_email_verification'),
    path('account/verification-sent/', EmailVerificationSentView.as_view(), name='email_verification_sent'),
    path('account/verify-email-otp/', email_verification_otp, name='email_verification_otp'),
    path('account/verify-email/<uuid:token>/', verify_email, name='verify_email'),
    path('account/update-status/', update_user_status, name='update_user_status'),
    path('account/presence-status/', update_presence_status, name='update_presence_status'),
    path('notifications/mark-read/', mark_notifications_read, name='mark_notifications_read'),
    path('notifications/feed/', notifications_feed, name='notifications_feed'),
    path('notifications/', notifications_list, name='notifications_list'),
    path('account/password-change/', SecurePasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', SecurePasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        SecurePasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/complete/',
        PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('dashboard/', dashboard, name='dashboard'),
    path('development/', development_hub, name='development_hub'),
    path('development/patch-notes/', development_patch_notes, name='development_patch_notes'),
    path('development/patch-notes/<int:patch_note_id>/edit/', development_patch_note_update, name='development_patch_note_update'),
    path('development/patch-notes/<int:patch_note_id>/delete/', development_patch_note_delete, name='development_patch_note_delete'),
    path('development/patch-notes/<int:patch_note_id>/comment/', development_patch_note_comment_add, name='development_patch_note_comment_add'),
    path('development/patch-notes/<int:patch_note_id>/like/', development_patch_note_toggle_like, name='development_patch_note_toggle_like'),
    path('development/patch-notes/comments/<int:comment_id>/edit/', development_patch_note_comment_edit, name='development_patch_note_comment_edit'),
    path('development/patch-notes/comments/<int:comment_id>/delete/', development_patch_note_comment_delete, name='development_patch_note_comment_delete'),
    path('development/feedback/<int:feedback_id>/comment/', development_feedback_add_comment, name='development_feedback_add_comment'),
    path('development/feedback/<int:feedback_id>/status/', development_feedback_update_status, name='development_feedback_update_status'),
    path('development/feedback/<int:feedback_id>/delete/', development_feedback_delete, name='development_feedback_delete'),
    path('system/', system_hub, name='system_hub'),
    path('system/backups/run/', system_backup_run_now, name='system_backup_run_now'),
    path('system/backups/<int:backup_id>/restore/', system_backup_restore, name='system_backup_restore'),
    path('system/backups/<int:backup_id>/delete/', system_backup_delete, name='system_backup_delete'),
    path('system/backups/<int:backup_id>/open/', system_backup_open, name='system_backup_open'),
    path('system/backups/<int:backup_id>/download/', system_backup_download, name='system_backup_download'),
    path('profile/', profile_page, name='profile_page'),
    path('support/lockouts/', support_lockout_center, name='support_lockout_center'),
    path('support/tickets/', support_tickets_list, name='support_tickets_list'),
    path('support/tickets/create/', support_ticket_create, name='support_ticket_create'),
    path('support/tickets/<int:ticket_id>/', support_ticket_detail, name='support_ticket_detail'),
    path('support/tickets/<int:ticket_id>/message/', support_ticket_add_message, name='support_ticket_add_message'),
    path('support/tickets/bulk/archive/', support_tickets_bulk_archive, name='support_tickets_bulk_archive'),
    path('support/tickets/bulk/delete/', support_tickets_bulk_delete, name='support_tickets_bulk_delete'),
    path(
        'support/tickets/<int:ticket_id>/priority/requested/',
        support_ticket_update_requested_priority,
        name='support_ticket_update_requested_priority',
    ),
    path(
        'support/tickets/<int:ticket_id>/support-update/',
        support_ticket_update_support,
        name='support_ticket_update_support',
    ),
    path('users/', users_list, name='users_list'),
    path('clients/', clients_list, name='clients_list'),
    path('fund-requests/', fund_requests_list, name='fund_requests_list'),
    path('finance/', finance_dashboard, name='finance_dashboard'),
    path('finance/reimburstment/', finance_reimburstment, name='finance_reimburstment'),
    path('finance/summary-request/', finance_summary_request, name='finance_summary_request'),
    path('fund-requests/records/', fund_request_records, name='fund_request_records'),
    path('fund-requests/records.pdf', fund_request_records_pdf, name='fund_request_records_pdf'),
    path('fund-requests/records.csv', fund_request_records_csv, name='fund_request_records_csv'),
    path('liquidation/', liquidation_page, name='liquidation_page'),
    path('liquidation/<int:liquidation_id>/pdf/', liquidation_pdf, name='liquidation_pdf'),
    path('liquidation/<int:liquidation_id>/download/', liquidation_download, name='liquidation_download'),
    path('liquidation/bulk/print/', liquidation_bulk_print, name='liquidation_bulk_print'),
    path('liquidation/bulk/download/', liquidation_bulk_download, name='liquidation_bulk_download'),
    path('fund-requests/<int:request_id>/review/', fund_request_review, name='fund_request_review'),
    path('fund-requests/<int:request_id>/review/pdf/', fund_request_review_pdf, name='fund_request_review_pdf'),
    path('fund-requests/<int:request_id>/print/', fund_request_print, name='fund_request_print'),
    path('fund-requests/<int:request_id>/client-preview/', fund_request_client_side_preview, name='fund_request_client_side_preview'),
    path('fund-requests/<int:request_id>/document/', fund_request_document, name='fund_request_document'),
    path('fund-requests/<int:request_id>/document/download/', fund_request_document_download, name='fund_request_document_download'),
    path('fund-requests/bulk/print/', fund_request_bulk_print, name='fund_request_bulk_print'),
    path('fund-requests/bulk/download/', fund_request_bulk_download, name='fund_request_bulk_download'),
    path('fund-request-templates/guide/', fund_request_template_guide, name='fund_request_template_guide'),
    path('fund-request-templates/<int:template_id>/preview/', fund_request_template_preview, name='fund_request_template_preview'),
    path('fund-request-templates/<int:template_id>/preview/pdf/', fund_request_template_preview_pdf, name='fund_request_template_preview_pdf'),
    path('clients/<int:client_id>/quick-view/', clients_quick_view, name='clients_quick_view'),
    path('clients/create/', clients_create, name='clients_create'),
    path('clients/<int:client_id>/quotation/', clients_quote, name='clients_quote'),
    path('clients/<int:client_id>/quotation/<int:quotation_id>/document/', clients_quotation_document, name='clients_quotation_document'),
    path('clients/<int:client_id>/quotation/bulk-delete/', clients_quotations_bulk_delete, name='clients_quotations_bulk_delete'),
    path('clients/<int:client_id>/edit/', clients_update, name='clients_update'),
    path('clients/<int:client_id>/delete/', clients_delete, name='clients_delete'),
    path('clients/deletion-requests/<int:request_id>/approve/', clients_deletion_request_approve, name='clients_deletion_request_approve'),
    path('clients/deletion-requests/<int:request_id>/reject/', clients_deletion_request_reject, name='clients_deletion_request_reject'),
    path('clients/bulk-delete/', clients_bulk_delete, name='clients_bulk_delete'),
    path('clients/bulk-status/', clients_bulk_update_status, name='clients_bulk_update_status'),
    path('assets/', assets_list, name='assets_list'),
    path('assets/departments/', assets_departments_list, name='assets_departments_list'),
    path('assets/departments/create/', assets_department_create, name='assets_department_create'),
    path('assets/departments/<int:department_id>/edit/', assets_department_update, name='assets_department_update'),
    path('assets/departments/<int:department_id>/delete/', assets_department_delete, name='assets_department_delete'),
    path('assets/departments/bulk-delete/', assets_departments_bulk_delete, name='assets_departments_bulk_delete'),
    path('assets/items/create/', assets_item_create, name='assets_item_create'),
    path('assets/items/<int:item_id>/edit/', assets_item_update, name='assets_item_update'),
    path('assets/items/<int:item_id>/delete/', assets_item_delete, name='assets_item_delete'),
    path('assets/items/bulk-delete/', assets_items_bulk_delete, name='assets_items_bulk_delete'),
    path('assets/items/<int:item_id>/variants/bulk-delete/', assets_variants_bulk_delete, name='assets_variants_bulk_delete'),
    path('assets/items/<int:item_id>/variants-modal/', assets_item_variants_modal, name='assets_item_variants_modal'),
    path('assets/item-types/', assets_item_types_list, name='assets_item_types_list'),
    path('assets/item-types/create/', assets_item_type_create, name='assets_item_type_create'),
    path('assets/item-types/<int:item_type_id>/edit/', assets_item_type_update, name='assets_item_type_update'),
    path('assets/item-types/<int:item_type_id>/delete/', assets_item_type_delete, name='assets_item_type_delete'),
    path('assets/item-types/bulk-delete/', assets_item_types_bulk_delete, name='assets_item_types_bulk_delete'),
    path('assets/tags/generate/', assets_generate_tags, name='assets_generate_tags'),
    path('assets/tags/<int:batch_id>/document/', assets_tag_document, name='assets_tag_document'),
    path('assets/tags/<int:batch_id>/delete/', assets_tag_batch_delete, name='assets_tag_batch_delete'),
    path('assets/tags/bulk-delete/', assets_tag_batches_bulk_delete, name='assets_tag_batches_bulk_delete'),
    path('assets/internet-accounts/', assets_company_accounts, name='assets_company_accounts'),
    path('assets/internet-accounts/submit/', assets_company_account_submit, name='assets_company_account_submit'),
    path('assets/internet-accounts/<int:account_id>/reveal/', assets_company_account_reveal, name='assets_company_account_reveal'),
    path('accountability/', accountability_list, name='accountability_list'),
    path('accountability/borrow/', accountability_create, name='accountability_create'),
    path('accountability/reports/summary/', accountability_report_summary, name='accountability_report_summary'),
    path('accountability/reports/summary.csv', accountability_report_summary_csv, name='accountability_report_summary_csv'),
    path('accountability/reports/list/', accountability_report_list, name='accountability_report_list'),
    path('accountability/reports/list.csv', accountability_report_list_csv, name='accountability_report_list_csv'),
    path('accountability/<int:accountability_id>/decide/', accountability_decide, name='accountability_decide'),
    path('accountability/pending/bulk-decide/', accountability_pending_bulk_decide, name='accountability_pending_bulk_decide'),
    path('accountability/item-autofill/', accountability_item_auto_fill, name='accountability_item_auto_fill'),
    path('accountability/<int:accountability_id>/return/', accountability_return, name='accountability_return'),
    path('accountability/records/bulk-action/', accountability_records_bulk_action, name='accountability_records_bulk_action'),
    path('users/create/', users_create, name='users_create'),
    path('users/<int:user_id>/quick-profile/', users_quick_profile, name='users_quick_profile'),
    path('users/<int:user_id>/edit/', users_update, name='users_update'),
    path('users/<int:user_id>/delete/', users_delete, name='users_delete'),
    path('users/bulk-delete/', users_bulk_delete, name='users_bulk_delete'),
    path('users/bulk-status/', users_bulk_update_status, name='users_bulk_update_status'),
    path('users/bulk-role/', users_bulk_update_role, name='users_bulk_update_role'),
    path('roles/', roles_list, name='roles_list'),
    path('roles/create/', roles_create, name='roles_create'),
    path('roles/<int:role_id>/edit/', roles_update, name='roles_update'),
    path('roles/<int:role_id>/delete/', roles_delete, name='roles_delete'),
]
